name: CI_$(date:yyyyMMdd)$(rev:.r)

# Re-enable trigger once Full build not deploying every time
trigger: none
#trigger:
#  branches: 
#    include:
#    - main
#  paths:
#    exclude:
#    - Quizzy.Deployment/*
#    - .gitignore
#    - Full.yaml
#    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  clientAppPath: 'Quizzy.WebApp\ClientApp'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Server
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build All'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '-c $(buildConfiguration)'

  - job: ClientApp
    steps:
    - task: NodeTool@0
      displayName: 'Ensure Node Installed'
      inputs:
        versionSpec: '12.x'
    - task: Npm@1
      displayName: 'Install ClientApp packages'
      inputs:
        command: 'install'
        workingDir: $(clientAppPath)        
    - task: Npm@1
      displayName: 'Build ClientApp'
      inputs:
        command: 'custom'
        workingDir: $(clientAppPath)
        customCommand: 'run build'

#- task: DotNetCoreCLI@2
#  displayName: 'Unit Tests'
#  inputs:
#    command: 'test'
#    projects: '**/*[Tt]ests/*.csproj'
#    arguments: '-c $(buildConfiguration) --no-build'